language: python

python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"
 - "nightly"
 - "pypy3"

matrix:
  allow_failures:
    # those "upcoming" python versions are informational
    - python: nightly
    - python: "pypy3"

sudo: false

addons:
  apt:
    packages:
      # gfortran is needed to build the examples
      - gfortran

env:
  matrix:
    - USE_PIP=ON
    - USE_PIP=OFF

script:
  # install latest release from pip ###########################################
  # .. or install from source
  #
  # note: since this is executed in a virtualenv
  #       we can not add "--user"
  - if [ "$USE_PIP" == "ON" ]; then
      pip install Forthon;
    else
      python3 setup.py install;
    fi
  # now build some examples ###################################################
  #
  - cd example
  - make
  # broken legacy example:
  # - cd ../example2
  # - make FORTHON=Forthon3
  - cd ../simpleexample
  - make
  - python3 run_forthon_example.py
  - cd ..
