#!/usr/bin/env tcsh
git pull

python -c "import version;version.update()"
set vvv=`python version.py`

git commit -a -m "version $vvv"
git tag $vvv
git push --tags

git archive --worktree-attributes --format=tar --prefix=Forthon-$vvv/ $vvv | gzip > Forthon-$vvv.tgz


scp Forthon-$vvv.tgz docs/index.html License.txt grote@hifweb:/web/html/Forthon
ssh hifweb "chmod -R go+rX /web/html/Forthon"
rm -f Forthon-$vvv.tgz version.pyc

# --- upload to Pypi
python setup.py sdist upload
