#!/bin/env tcsh
cvs update
(cd .. ; tar --exclude update --exclude build --exclude \*.so --exclude CVS --exclude version.pyc -czf Forthon.tgz Forthon)
#set ttt=`python -c "import time;t = time.localtime(time.time());print '%s%02d%02d'%(t[0],int(t[1]),int(t[2]))"`
python -c "import version;version.update()"
set vvv=`python version.py`
scp ../Forthon.tgz dave@hifweb:/web/html/Forthon/Forthon-$vvv.tgz
scp docs/index.html dave@hifweb:/web/html/Forthon
#ssh hifweb "ln -sf /web/html/Forthon/Forthon-$vvv.tgz /web/html/Forthon/Forthon.tgz"
ssh hifweb "chmod -R go+rX /web/html/Forthon"
rm -f ../Forthon.tgz version.pyc

